### ISSUE TITLE
Create Hugo template for about

### ISSUE THREAD

**Issue by robertmeta** [vim-advent-calendar/vimways.org#1]
We need a hugo template for about -- we can either build it from scratch or start from a hugo theme we like which is probably a lot less work.

**Comment by romainl** [comment]
I'll google it anyway but is there a theme repository you like?

**Comment by romainl** [comment]
let's take a look at https://themes.gohugo.io/

**Comment by HugoNikanor** [comment]
Oh, this isn't about me.
-- 
Hugo Hörnquist

**Comment by robertmeta** [comment]
Haha, sorry @HugoNikanor -- yeah, we are using Hugo for the site generator, so expect stuff to continue to be confusing :)

**Comment by romainl** [comment]
DONE: https://vimways.org/about
