### ISSUE TITLE
Repo needs info about how to build the site

### ISSUE THREAD

**Issue by shlomif** [vim-advent-calendar/vimways.org#10]
The repo needs info about how to build the site from the sources. A [CI service config](https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ.mdwn#what-do-continuous-integration-ci-services-such-as-travis-ci-jenkins-or-appveyor-provide) will be helpful as well.

**Comment by romainl** [comment]
I've added some basic information to the README.
