### ISSUE TITLE
Obscure author email addresses

### ISSUE THREAD

**Issue by djmoch** [vim-advent-calendar/vimways.org#14]
I don't know enough about how Hugo works to put a PR together, but I know Markdown supports mangling email addresses such that bots wouldn't recognize it, while leaving the presentation unchanged. See [here](https://daringfireball.net/projects/markdown/syntax#autolink) for more description.

**Comment by romainl** [comment]
Superficial tests show that Hugo doesn't support automatic links. I'll need to look further into it if it's considered necessary but with today's phantomjs-based scrappers, such techniques are pretty much pointless.

**Comment by djmoch** [comment]
Okay. Thanks for looking into it. I've had a feeling this isn't as
useful as it once was, but don't have anything to back that up with so
I've just kept doing it.
