### ISSUE TITLE
`checktime` is an Ex command, not an option

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/vimways.org#17]
@swalladge, here is an issue spotted by a redditor: 

> Thanks for the article!
>
> I'm especially glad to get rid of the annoying message ( the file has been changed). However, checktime seems to be a command rather than an option. Is there a small mistake in your article or am I missing something?
>
> I get E518: unknown option: checktime

**Comment by swalladge** [comment]
I'm on it. :+1:

**Comment by romainl** [comment]
Thanks!
