### ISSUE TITLE
Use g:Hostname instead of g:host

### ISSUE THREAD

**Issue by chrisbra** [vim-advent-calendar/vimways.org#23]
Hi,
in the latest article, gagbo-truly-cross-platform.md, the variable `g:host` is set, but everywhere else it refers to `g:Hostname`.

Also, I think it might make sense to check `$HOSTNAME`, as certain shells set it (bash e.g. does it), so one does not need to call `hostname`. Just want to mention it.

**Comment by djmoch** [comment]
Actually, is there anything that would prevent just using Vim’s built in `hostname()` in a cross-platform context?

**Comment by chrisbra** [comment]
Oh yes, that should also work

**Comment by romainl** [comment]
The author fixed the variable name. I pinged him about `hostname()`.

**Comment by gagbo** [comment]
I didn't know about `hostname()`. I did not think of this because I only call this once or twice and this was not the worst offendant in my startuptime. Thanks for the heads up !
