### ISSUE TITLE
<C-...> is crowded

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/vimways.org#27]
> pepper_chico:
> on mappings, I generally think it's worth mentioning that <c-foo> is all taken, and don't try ctrl-num, ctrl-special, etc http://vimhelp.appspot.com/vim_faq.txt.html#faq-20.5

**Comment by fcpg** [comment]
The "what key to map" question was initially part of the draft, but I decided to leave it out as I was not sure it add much value. Users tend to know what they want to map, and they have different preferences.

As for the the control keys, it is often terminal-related eg. some will work with gvim. Then, there are 'timeout' and 'ttimeout', CSI, OSC, bracketed paste, influence of screen/tmux etc.

All these questions are interesting and could have had their place; they may be the topic on some article of its own, actually.
