### ISSUE TITLE
Dec 8 mapping issue

### ISSUE THREAD

**Issue by habamax** [vim-advent-calendar/vimways.org#31]
Can't make `p` mapping work out of Dec 8 article:

     xnoremap <silent> p p:if v:register == '"'<Bar>let @@=@0<Bar>endif<cr>

After first `p` all my key presses goes to the vim cmdline:

https://imgur.com/pC65RJa

**Comment by fcpg** [comment]
The Vim notation `<Bar>` and `<cr>` don't seem to be recognized/expanded correctly.

Could be a 'cpo' issue, or some non-ASCII formatting when copy-pasting from browser to gvim.

**Comment by habamax** [comment]
Looks like that, I have entered this mapping manually and now it works.
