### ISSUE TITLE
Dec 10 problem

### ISSUE THREAD

**Issue by linusboyle** [vim-advent-calendar/vimways.org#35]
Hello!
In the article, it says:
> This changes the behavior in the way we need. To be tidy, we should clear the variable away again afterwards in $VIMRUNTIME/after/indent/html.vim, since after the stock file has run, this global variable has done its job:

shouldn't it be `.vim/after/indent/html.vim`? I think it's a typo here

**Comment by tejr** [comment]
@linusboyle Thanks!

**Comment by linusboyle** [comment]
@tejr fixed :+1:
