### ISSUE TITLE
Suggestions for: 'Opening Non-Vim File Formats'

### ISSUE THREAD

**Issue by flatcap** [vim-advent-calendar/vimways.org#46]
There are 5 instances of `:!mkdir -p ~/.vim/ftdetect/FILE`
They'll create a **directory** with the name you wanted as a file.
It might be better to just: `:!mkdir -p ~/.vim/ftdetect` once at the beginning, then assume it exists later.

Commit: 5d4110a adds a 79 **MB** file, `example.gif` that isn't referenced anywhere.
That's a bit antisocial to anyone wanting to work with the repo.
It's considered 'bad form' to alter the history of public git repos, but it'd better to eliminate the file now, rather than later.

A minor formatting issue, I'd change
- `*.txt, et al.`
to
- `*.txt`, et al.

**Comment by connermcd** [comment]
Agree with all suggestions. I'd a mind to remove the gif myself but as you stated did not want to rebase a repo that I don't own.

**Comment by flatcap** [comment]
**NOTE** This will invalidate everyone's fork of this repo.

I frequently mess about with my own repos, but I'm feeling a bit anxious messing with someone elses :-)

These commands will filter out the file we want to remove.
I considered `git rebase --interactive`, but that will change the commit graph.

```sh
# Go through every commit (this is overkill) and delete the 'example.gif'
git filter-branch --prune-empty -d /tmp/scratch --index-filter "git rm --cached -f --ignore-unmatch content/2018/opening-other-file-formats/example.gif" -- --all

# Get rid of the 'original' refs that `filter-branch` saved
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d

# Garbage collect the repo
git reflog expire --expire=now --all
git gc --prune=now

du -sh

# Check the history looks OK
git log --graph

# Commit the changes
git push --force origin master:master
```

I've tried this several times, successfully.
Good luck.

**Comment by connermcd** [comment]
I've made the suggested edits and a complete rebase/rewrite expunging the demon gif on my fork. I can't open a pull request since they are completely different commit histories, but it can be applied by someone with access to the main repo. Again, this will invalidate all current forks of the project.

**Comment by romainl** [comment]
I think this can be closed, now. Thank you @flatcap @nd @connermcd .
