### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by af** [vim-advent-calendar/vimways.org#6]
Hi,

Thanks for putting this project together! It'd be really handy to have an RSS feed for the site. It looks like the site is built with Hugo (I think?), which ships with some support for RSS: https://gohugo.io/templates/rss/

Is there any reason not to enable this? I could try to put a PR together in the next 24-48 hours, but haven't used Hugo before so I'm not sure if there's some complexity I'm missing here

**Comment by romainl** [comment]
Hi, Hugo is kind enough to generate an RSS feed automatically: https://vimways.org/index.xml, but I still need to add a link in the footer.

This should be quick.

**Comment by romainl** [comment]
Aaaand it's done. Thanks for the heads up.
