### ISSUE TITLE
Hugo link in README is dead

### ISSUE THREAD

**Issue by axelf4** [vim-advent-calendar/vimways.org#60]
The link to Hugo in the README is missing:

> `Vimways is a static website built with [Hugo]().`

[Link to relevant line in README.md](https://github.com/vim-advent-calendar/vimways.org/blame/4c4bf49fcfc62ad0d942302363edaf455aa79e42/README.md#L9)

Just a nitpick. 😉 Thanks for putting this together!

**Comment by romainl** [comment]
Thanks, and keep nitpicking!
