### ISSUE TITLE
The asciicasts embedded into https://vimways.org/2018/the-power-of-diff/ are disabled

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/vimways.org#64]
> This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by chrisbra** [comment]
what do you need me to do here?

**Comment by robertmeta** [comment]
https://blog.asciinema.org/post/ (attached to an account will fix for future)

**Comment by romainl** [comment]
> what do you need me to do here?

We need you to claim those asciicasts so that they can be embedded again.

**Comment by chrisbra** [comment]
I did `asciinema auth`, but that did not make the recordings re-appear. I even created an account. I am not sure I can do anything more

**Comment by chrisbra** [comment]
I've contacted support, let's see, if they can fix it.

**Comment by romainl** [comment]
@chrisbra thanks.

**Comment by robertmeta** [comment]
@romainl you might want to add a note to authors (and double-check) that all asciinema's are non-anon so they will persist.

**Comment by romainl** [comment]
@robertmeta will do.

**Comment by chrisbra** [comment]
apparently support is not very active, haven't received any response yet.

**Comment by romainl** [comment]
Acknowledged.

**Comment by chrisbra** [comment]
should be back now

**Comment by romainl** [comment]
Confirmed, thanks.
